### ISSUE TITLE
Permitir 1,N Archivos

### ISSUE THREAD

**Issue by jonyram1988** [VIDALYCONTRERASLIMITADA/jquery.fileuploadValora.js#11]

**Comment by jonyram1988** [comment]
Por favor @realaceone dar prioridad a este request para así no quedar cojo en posibles solicitudes.

**Comment by realaceone** [comment]
@jonyram1988 Realizado. Sin embargo, existen known Issues en esta versión con el parámetro multiple: true.

**Comment by realaceone** [comment]
Realizado
