### ISSUE TITLE
Signo menos y signo Más en Cero Faltas

### ISSUE THREAD

**Issue by jonyram1988** [VIDALYCONTRERASLIMITADA/jquery.fileuploadValora.js#18]
Si salimos y entramos a otro artículo, salimos y volvemos a entrar al artículo 144, aparece el signo +

![image](https://cloud.githubusercontent.com/assets/3934223/26557479/b7856bec-446f-11e7-9258-6f1eb36a09d7.png)

![image](https://cloud.githubusercontent.com/assets/3934223/26557484/bd2cee9e-446f-11e7-8dcf-96791782f1cb.png)

**Comment by realaceone** [comment]
Realizado y se actualizará documentación.

**Comment by realaceone** [comment]
Documentación actualizada y se cierra Issue

**Comment by realaceone** [comment]
Queda en estado QA hasta finalizar SPRINT 2

**Comment by jonyram1988** [comment]
Se cierra!
