### ISSUE TITLE
opcion para marcar principal

### ISSUE THREAD

**Issue by frecifue** [VIDALYCONTRERASLIMITADA/jquery.fileuploadValora.js#22]
una opción de mejora seria poder marcar un archivo como principal, debido a que este requerimiento se usa con frecuencia

**Comment by realaceone** [comment]
@frecifue Se tomará en consideración para un futuro release.

**Comment by realaceone** [comment]
@frecifue Analizando en el nuevo sprint, esto es posible desarrollarlo a través de la variable template del plugin. Se cierra ya que no aplica.
